SciML/DataInterpolations.jl

.gitignore, Project.toml, src/plot_rec.jl
With this PR, you should be able to do:
```julia
@series
seriestype := :loess # any *_interp or *_spline also
x := xs
y := ys
end
```
and have it "just work", generating a smoothed series.
=> Implement series recipes for interpolations

Project.toml, src/interpolation_utils.jl
=> Up DataFrames compat and fix depwarns

test/interpolation_tests.jl
Should fix MacOS FP issues @ChrisRackauckas
=> Approx test for BSplineApprox

Project.toml, src/interpolation_alg/interpolation_methods.jl, src/interpolation_utils.jl
=> Some performance improvements for ZeroSpline

.travis.yml, Project.toml, src/DataInterpolations.jl, src/interpolation_utils.jl, test/interpolation_tests.jl
This also fixes a deprecation warning
=> Remove some deps

src/caches/interpolation_caches.jl, src/interpolation_alg/interpolation_methods.jl, test/interpolation_tests.jl
and fix `dir=:left` to include the data points in the interpolation. I've also added some comments describing `dir`. Adding proper documentation will require more effort. Just wanted this in before Sunday.
=> Fix dir=:left in ZeroSpline

Project.toml, src/interpolation_utils.jl, src/plot_rec.jl
Also fix some issues with the recipes.
cc @ChrisRackauckas
=> Implement Akima recipe and shorthands

.travis.yml, README.md
Add badge. Bump testing to Julia 1.3.
=> Fix coverage submission

Project.toml
I've also activated CompatHelper so there might be another round of bound updates after this PR.
=> Set bounds on dependencies

Project.toml
I accidentally added Weave to the project in the #58
=> Remove Weave as a dependency

src/interpolation_methods.jl
=> Use searchsortedlast for BSplines

src/interpolation_caches.jl
Solves issue with SplineLayer in DiffEqFlux.
=> change in diff

src/interpolation_methods.jl
This should improve the time complexity from O(t) to O(log(t)).
=> Use binary search to find time index

src/interpolation_methods.jl, test/interpolation_tests.jl
The current implementation causes an out of bounds error for upper extrapolation. I've also added tests.
=> Fix index calculation for upper extrapolation

test/regularization.jl
=> remove irrelevant tests from test/regularization.jl

Project.toml, src/DataInterpolations.jl, test/interface.jl
Fix https://github.com/SciML/ModelingToolkit.jl/issues/1354
=> Fix register

test/interpolation_tests.jl
https://github.com/JuliaLang/julia/issues/45511 strikes
=> fix test on 1.9

Project.toml, ext/SymbolicsExt.jl, src/DataInterpolations.jl
Also tested on 1.8 and is backwards compatible.
=> Make Symbolics a conditional dependency in 1.9

Project.toml, README.md, example/DataInterpolations.jmd, ext/DataInterpolationsRegularizationToolsExt.jl, src/DataInterpolations.jl, test/regularization.jl
- Move `RegularizationSmooth` definitions to the extension
- Extension loads when RegularizationTools is loaded
=> feat: add `DataInterpolationsRegularizationToolsExt` extension

Project.toml
See https://github.com/SciML/DataInterpolations.jl/pull/178#issuecomment-1732358426
=> should work with QuadGK 2.9.1

ext/DataInterpolationsSymbolicsExt.jl, test/derivative_tests.jl
updated version of https://github.com/SciML/DataInterpolations.jl/pull/170 and added a test
@ChrisRackauckas is there anything else needed for this PR?
=> First order symbolic derivative

src/derivatives.jl, test/derivative_tests.jl
=> Fix BSpline Derivative at the beginning

ext/DataInterpolationsChainRulesCoreExt.jl, ext/DataInterpolationsOptimExt.jl, ext/DataInterpolationsRegularizationToolsExt.jl, src/DataInterpolations.jl, src/interpolation_caches.jl, src/interpolation_utils.jl, test/interpolation_tests.jl, test/regularization.jl, test/show.jl
=> Run JuliaFormatter.format()

src/DataInterpolations.jl, test/derivative_tests.jl
Fixes https://github.com/SciML/DataInterpolations.jl/issues/229
=> Promote element type for ForwardDiff jacobians

Project.toml, ext/DataInterpolationsOptimExt.jl, ext/DataInterpolationsRegularizationToolsExt.jl, ext/DataInterpolationsSymbolicsExt.jl, src/DataInterpolations.jl, src/derivatives.jl, test/derivative_tests.jl
=> feat: add order arg for second order derivatives

NEWS.md, docs/Project.toml
=> chore: format NEWS.md and bump DataInterpolations version in docs

docs/src/methods.md
=> docs: add AkimaInterpolation in methods page

LICENSE.md
Ref comment in https://github.com/openjournals/joss-reviews/issues/6856#issuecomment-2161228883
and following the template in https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt
=> chore: update LICENSE

src/DataInterpolations.jl, test/interpolation_tests.jl
=> refactor: add methods for computing with vector of timepoints vector of vectors and matrices

docs/src/inverting_integrals.md, src/integral_inverses.jl, src/online.jl, test/online_tests.jl
Small follow-up of https://github.com/SciML/DataInterpolations.jl/pull/282.
=> Cleanup of Invert integrals

README.md, docs/src/index.md, docs/src/manual.md, docs/src/methods.md, src/DataInterpolations.jl, src/interpolation_caches.jl, src/interpolation_utils.jl, test/interpolation_tests.jl
Fixes https://github.com/SciML/DataInterpolations.jl/issues/283
Fixes https://github.com/SciML/DataInterpolations.jl/issues/292
=> add `PCHIPInterpolation`

src/interpolation_caches.jl
=> docs: small cleanup of pchip docstrings

src/parameter_caches.jl, test/interpolation_tests.jl
Fix https://github.com/SciML/DataInterpolations.jl/issues/302
=> Nan slope fix

docs/src/index.md
It was mentioned in JOSS review: https://github.com/openjournals/joss-reviews/issues/6917#issuecomment-2230677031, 4th point.
=> docs: add statement of need in docs

docs/Project.toml, docs/make.jl, docs/src/symbolics.md
Came up in JOSS review - https://github.com/openjournals/joss-reviews/issues/6917#issuecomment-2230677031
=> docs: small tutorial on using DataInterpolations with Symbolics/MTK

joss/paper.md
=> docs: add reference to symbolics/mtk tutorial in joss paper

joss/paper.md
Ref - https://github.com/openjournals/joss-reviews/issues/6917#issuecomment-2275866714
=> docs: fix references, spacing and language in the example section

Project.toml
So that a release with the fixes in #376 is triggered
=> Bump Project.toml to 7.0.1

ext/DataInterpolationsChainRulesCoreExt.jl, test/zygote_tests.jl
=> refactor: zygote rules for matrix inputs

docs/src/symbolics.md
=> Update MTK suggestion to use the stdlib

docs/src/symbolics.md
=> docs: fix typo
