src/interpolation_methods.jl
test/interpolation_tests.jl

This fixes an error of indexing that appearead when evaluating the BSpline on the final point used for interpolation (`A(t[end])` on interpolation_tests.jl). Possibly caused when `findfirst` was substituted by `searchsortedlast`.

Fix BSpline evaluation error on final point

---

src/interpolation_methods.jl

This allows you to interpolate, e.g., vectors of `SVector`. I have only tried this with linear interpolations, which works fine.

remove type restrictions on the space of the interpolation

---

.travis.yml
Project.toml
README.md
src/DataInterpolations.jl
src/derivatives.jl
src/interpolation_caches.jl
src/interpolation_methods.jl
test/derivative_tests.jl
test/runtests.jl

Follow up from https://github.com/SciML/DiffEqFlux.jl/pull/380

Add derivatives for the splines

---

Project.toml
src/DataInterpolations.jl

These happen to be the ones that Zygote could already handle and do not have numerical stability issues.
https://github.com/SciML/DiffEqFlux.jl/blob/e7cbc6170429c2e72b59f0bdda832845431d378f/src/spline_layer.jl#L19-L20
We should extend the rrule to include derivatives of the coefficients instead of the `DoesNotExist()` as it will decrease the complexity on the source code rewriting and ensure we get numerical stability, but for now this gets tests passing.

Skip differentiation of terms needed in SplineLayer

---

.github/workflows/CI.yml
Project.toml
src/DataInterpolations.jl
test/interface.jl

@yingboma do you know why the printing is weird?
```julia
julia> using Symbolics; u = 2.0collect(1:10); t = 1.0collect(1:10);
julia> A = LinearInterpolation(u,t);
julia> @variables t
1-element Vector{Num}:
t
julia> A(t)
[2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0](t)
julia> Symbolics.operation(A(t))
20-element LinearInterpolation{Vector{Float64}, Vector{Float64}, true, Float64}:
2.0
4.0
6.0
8.0
10.0
⋮
6.0
7.0
8.0
9.0
10.0
julia> Symbolics.arguments(A(t))
1-element Vector{Num}:
t
```

Register Interpolations for Symbolics

---

Project.toml
src/DataInterpolations.jl
src/integrals.jl
test/integral_tests.jl
test/runtests.jl

DataInterpolations already has support for computing the analytical derivative at any given point. This PR is a first step towards providing the same for integration.
I've computed the analytical integrals of the interpolation functions with an ungodly mix of Symbolics, Sympy, and copy-pasting, since Symbolics does [not yet](https://julialang.org/jsoc/gsoc/symbolics/#symbolic_integration) have a heuristic symbolical integration package like Sympy does, so was only used to extract the equations from the existing code.
This PR only adds integrals for a subset of the supported interpolations that seemed useful and easy to do. A future PR could extend this to more interpolations, but first I'll go back and put this functionality through its paces in CedarWaves.

add support for analytical integration of some interpolations

---

src/DataInterpolations.jl
src/online.jl
test/online_tests.jl
test/runtests.jl

This adds an `append!` implementation for a few simple interpolations so that they can be used in an online context.
It should be possible to implement this for a few more interpolations that are not global, such as Akima.
But I'll just put this out there to make sure I'm going in the right direction before doing tricky things to make online Akima work and then have to do it again based on feedback.
Some things I'm not totally sure about:
- maybe we should implement `push!`
- maybe the type bounds are too tight now
- it seems very eager to call the `AbstractVector` method and complain there is no `resize!` method.
- lagrange has an immutable length field
- which methods are amenable to appending data

add append! for online interpolation

---

src/interpolation_methods.jl
test/interpolation_tests.jl

Ran some benchmarks using a uniform step time and got 419 us and when using random time values (sorted) got 421 us so I don't see a noticable slowdown.

Add NaN support for 1D LinearInterpolation Fix #113

---

src/derivatives.jl
src/integrals.jl
src/interpolation_caches.jl
src/interpolation_methods.jl
test/derivative_tests.jl
test/integral_tests.jl
test/interpolation_tests.jl

Hello,
In using `DataInterpolations.jl` for my own application, I noticed that while `ConstantInterpolation`, `LinearInterpolation` and `QuadraticInterpolation` allow, for example:
```julia
u = [randn(4), randn(4), randn(4), randn(4), randn(4), randn(4)]
t = [0.0, 62.25, 109.66, 162.66, 205.8, 252.3]
A = ConstantInterpolation(u,t) # or LinearInterpolation(u,t) or QuadraticInterpolation(u,t)
```
or 
```julia
u = [randn(4,5), randn(4,5), randn(4,5), randn(4,5), randn(4,5), randn(4,5)]
t = [0.0, 62.25, 109.66, 162.66, 205.8, 252.3]
A = ConstantInterpolation(u,t) # or LinearInterpolation(u,t) or QuadraticInterpolation(u,t)
```
, `LagrangeInterpolation`, `QuadraticSpline`, `CubicSpline` do not allow this.
In this pull request, I modified these three functions so that `u` similar to the above …

LagrangeInterpolation, QuadraticSpline, CubicSpline for data with multiple channels

---

Project.toml
src/interpolation_methods.jl
test/interpolation_tests.jl

The fast path for linear interpolation when no interpolation is needed (time point is provided in vector) returned a different type which caused issues with types/performance with higher level code.
I ran some benchmarks and see no difference in performance.

Fix type stability issue with linear interpolation #113

---

src/derivatives.jl
test/derivative_tests.jl

Without this plotting the derivative looks bad (end point goes to zero) and this seems more correct.

Fix #119 Smooth Akima derivative at end points

---

Project.toml
example/DataInterpolations.jmd
src/interpolation_caches.jl
src/interpolation_methods.jl
test/interpolation_tests.jl

The current behaviour of QuadraticInterpolation chooses as the three points for the parabolic fit the two closest points to the interpolation point `t`, as well as the next point to the right (whenever possible, since you can't do this for the last subinterval); this is therefore a "forward-looking" behaviour. Another option is just as sensible, a priori: take the previous point to the left whenever possible, representing a "backward-looking" behavior. This PR adds this alternative behaviour as an option, while leaving the forward-looking one as the default if no mode is specified (thus users should see any numerical change at all, unless they explicitly opt in to the backward-looking mode). The proposed interface is 
```julia
I = QuadraticInterpolation(u,t)
I = …
```

Add backward-looking option for quadratic interpolation

---

Project.toml
src/derivatives.jl
src/integrals.jl
test/derivative_tests.jl
test/integral_tests.jl

In a [previous PR](https://github.com/PumasAI/DataInterpolations.jl/pull/121), I added a "backward" mode to QuadraticInterpolation, but I unwittingly missed updating derivatives and integrals. This PR fixes that omission by making the derivative() and the integral() consistent with the selected mode (instead of always having the forward-looking behavior).

Fix derivatives and integrals for backward QuadraticInterpolation

---

src/interpolation_methods.jl
test/interpolation_tests.jl

The check for `nan` prevented me from using matrices as values for the interpolation, this PR allows for that 
`any(isnan, x)` is not slower so the new check should be fine
```
julia> @btime isnan(x) setup=(x=randn())
1.873 ns (0 allocations: 0 bytes)
false
julia> @btime any(isnan, x) setup=(x=randn())
1.863 ns (0 allocations: 0 bytes)
false
```

allow array-valued linear interpolation

---

Project.toml
ext/DataInterpolationsSymbolicsExt.jl

ModelingToolkit throws errors when trying to print systems with interpolations due to calling `Base.nameof` on expression atoms.

Implement basic `Base.nameof` for interpolations

---

src/interpolation_caches.jl
test/interpolation_tests.jl

This PR enables ForwardDiff derivatives of interpolation results with respect to interpolator inputs, i.e.
```julia
using DataInterpolations, ForwardDiff
function f(c)
xs = 0.0:2.0:4.0
ys = [c * x for x in xs]
itp = CubicSpline(ys, xs)
return itp(c)
end
ForwardDiff.derivative(f, 2.0)
```
In the quadratic and cubic spline interpolators, the column vector `d` in the tridiagonal linear solve `tA\d` has element type `Real` when the coefficients are dual types. This happens because the first element of `d` will not be a dual type, due to the edge case.
https://github.com/PumasAI/DataInterpolations.jl/blob/7a4b5f2773b3957ca79adae63bf6dbfd9aee2a2f/src/interpolation_caches.jl#L125
To be as general as possible, this PR determines the type of the *second* element of `d` and then generates a zero …

fix ForwardDiff compatibillity with respect to coefficients

---

Project.toml

There seems to be an issue with QuadGK@2.9 - https://github.com/JuliaMath/QuadGK.jl/issues/89
Hence bounding the compat at 2.8

Compat bound QuadGK

---

docs/src/methods.md
ext/DataInterpolationsRegularizationToolsExt.jl
test/regularization.jl

`_interpolate` was defined but not properly extended in the extension

fix: extend `_interpolate` for `RegularizationSmooth`

---

src/derivatives.jl
src/interpolation_methods.jl
test/derivative_tests.jl
test/interpolation_tests.jl

This PR fixes:
1. Extrapolation for `BSplineInterpolation` and `BSplineApprox` - this is made constant equal to the endpoint
2. Derivative at right end point for `BSplineApprox`
3. Extrapolation of derivatives for `LinearInterpolation`, `QuadraticSpline`, `CubicSpline`,  `BSplineInterpolation` and `BSplineApprox`
Partial fix towards: https://github.com/SciML/DataInterpolations.jl/issues/175

Fix Extrapolation for methods

---

src/interpolation_utils.jl
test/interpolation_tests.jl

Bypass the `bracketstrictlymontonic` stage of the index lookup for ranges in `searchsorted...correlated`, because the corresponding `searchsorted...` functions for ranges in `Base` already do O(1) exact lookup without searching. This results in faster interpolation when `t` is a range. The first linear interpolation tests are also repeated for ranges.
Benchmark: 
```julia using DataInterpolations, BenchmarkTools
exec_times = Float64[]
for x in 3:9 
N = 10^x
u = rand(N)
t = 1:N
li = LinearInterpolation(u, t)
b = @benchmark $li(rand($t))
push!(exec_times, mean(b.times))
end
```
Results (the jump in latency in the PR at some points is probably because of cache misses as we're interpolating random elements):
Close #187

Bypass bracketing for AbstractRanges

---

Project.toml
ext/DataInterpolationsOptimExt.jl
ext/DataInterpolationsRegularizationToolsExt.jl
src/DataInterpolations.jl
src/show.jl
test/runtests.jl
test/show.jl

Example:
```julia
julia> LinearInterpolation(x, t)
LinearInterpolation with 5 points
┌──────┬─────┐
│ time │   u │
├──────┼─────┤
│  1.0 │ 1.0 │
│  2.0 │ 2.0 │
│  3.0 │ 3.0 │
│  4.0 │ 4.0 │
│  5.0 │ 5.0 │
└──────┴─────┘
```
fixes: #167

Add show methods

---

src/derivatives.jl
test/derivative_tests.jl

fix: Lagrange interpolations derivative

---

Project.toml
ext/DataInterpolationsChainRulesCoreExt.jl
ext/DataInterpolationsOptimExt.jl
ext/DataInterpolationsRegularizationToolsExt.jl
src/DataInterpolations.jl
src/derivatives.jl
src/integrals.jl
src/interpolation_caches.jl
src/interpolation_methods.jl
src/interpolation_utils.jl
src/plot_rec.jl
test/derivative_tests.jl
test/interpolation_tests.jl
test/regularization.jl

This PR does the following:
1. Add derivatives for `RegularizationSmooth` using derivatives of CubicSplines as it fits a CubicSpline after solving the optimization problem
2. Add derivatives for `Curvefit` using ForwardDiff
3. Added tests for both
4. Added `extrapolate` keyword to both to make it consistent with other methods
5. Reorganized the extension files for more consistency
6. Formatted the repo
Partial fix towards https://github.com/SciML/DataInterpolations.jl/issues/175

Add derivatives for `RegularizationSmooth` and `Curvefit`

---

ext/DataInterpolationsOptimExt.jl
ext/DataInterpolationsRegularizationToolsExt.jl
src/DataInterpolations.jl
src/derivatives.jl
src/integrals.jl
src/interpolation_methods.jl
test/integral_tests.jl
test/interpolation_tests.jl

Add integrals for remaining methods

---

docs/src/interface.md

Update to include `extrapolate` keyword

docs: update interface tutorial

---

src/interpolation_caches.jl
test/interpolation_tests.jl

Fixes: #234 
Now we get the same outputs as scipy
```julia
julia> CubicS.(v)
20-element Vector{Float64}:
318.6243760456969
334.40200181048806
347.13345942996295
356.2838248343795
362.79265929502935
367.66363214151
371.88318244762684
376.04145340397156
380.33229231792177
384.9323162410631
390.002925359128
395.35553194322165
400.451560349822
404.7372180695537
407.7255576184023
410.46706709565404
415.5496701838955
425.6281355910744
443.20840335017215
467.3733539699478
```
https://en.wikiversity.org/wiki/Cubic_Spline_Interpolation
The first entry of the third column and last entry of first column in the tridiagonal matrix should have been zero.
For the tests, the polynomial mentioned in https://github.com/SciML/DataInterpolations.jl/blob/master/test/interpolation_tests.jl#L501 is not correct …

fix: CubicSpline's natural boundary conditions

---

src/interpolation_utils.jl

This would allow to use ForwardDiff for derivatives of BSplines
MWE:
```julia
using DataInterpolations, ForwardDiff
u = [14.7, 11.51, 10.41, 14.95, 12.24, 11.22]
t = [0.0, 62.25, 109.66, 162.66, 205.8, 252.3]
sd = t -> ForwardDiff.derivative(Base.Fix1(DataInterpolations.derivative, A), t)
sd(0.0)
```
Stacktrace:
```julia
ERROR: MethodError: no method matching Float64(::ForwardDiff.Dual{ForwardDiff.Tag{Base.Fix1{typeof(DataInterpolations.derivative), BSplineInterpolation{Vector{Float64}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Vector{Float64}, true, Float64}}, Float64}, Float64, 1})
Closest candidates are:
(::Type{T})(::Real, ::RoundingMode) where T<:AbstractFloat
@ Base rounding.jl:207
(::Type{T})(::T) where T<:Number
@ Core boot.jl:792
Float64(::Float32)
@ Base float.jl:261 …
```

fix: eltype of N in `spline_coefficients` to allow working with dual numbers

---

ext/DataInterpolationsOptimExt.jl
ext/DataInterpolationsRegularizationToolsExt.jl
ext/DataInterpolationsSymbolicsExt.jl
src/DataInterpolations.jl
src/integrals.jl
src/interpolation_caches.jl
src/interpolation_methods.jl
test/derivative_tests.jl
test/interface.jl
test/online_tests.jl

If `AbstractVector` subtyping is not removed, We get errors like:
```julia
julia> df2 = expand_derivatives(D2(f(τ)))
ERROR: Differentiation with array expressions is not yet supported
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:35
[2] occursin_info
@ ~/.julia/packages/Symbolics/Eas9m/src/diff.jl:67 [inlined]
[3] (::Symbolics.var"#254#256"{SymbolicUtils.BasicSymbolic{Real}, SymbolicUtils.BasicSymbolic{Real}})(a::LinearInterpolation{Vector{Float64}, Vector{Float64}, true, Float64})
@ Symbolics ~/.julia/packages/Symbolics/Eas9m/src/diff.jl:100
[4] iterate
@ ./generator.jl:47 [inlined]
[5] _collect(c::Vector{Any}, itr::Base.Generator{Vector{…}, Symbolics.var"#254#256"{…}}, ::Base.EltypeUnknown, isz::Base.HasShape{1})
@ Base ./array.jl:854
[6] collect_similar
@ ./array.jl:763 [inlined] …
```

refactor!: remove indexing dispatches and add dispatch for higher order derivatives with Symbolics

---

Project.toml
src/DataInterpolations.jl
test/regularization.jl

fixes #255 by replacing `AbstractInterpolation{T}` with parametric type in the `RegularizationSmooth` struct.
About the style, the modified line is too long, I'm not sure how to split it.
I'm not sure of the name of the parametric type either.

fix: remove abstract type from RegularizationSmooth 

---

src/DataInterpolations.jl
test/interpolation_tests.jl

fixes: #253
In DataInterpolations@v4, `eltype(interp)` returned `eltype(interp.u)` as it subtyped `AbstractVector` of type which is the eltype of `interp.u`
In DataInterpolations@v5, `eltype(interp)` returns `Any` as the subtyping to AbstractVector is removed, hence the issue. Fixing it to use `eltype(interp.u)`.
Added a few tests to ensure the returned vectors have the same type as `interp.u`.

fix: get element type from `interp.u` instead of  `interp`

---

joss/paper.bib
joss/paper.md

@ChrisRackauckas, @sipah00 - this is the initial draft of the JOSS paper for DataInterpolations.jl. Can you go through it and suggest any changes required?

docs: add joss paper

---

README.md

Removing this as directly indexing into the interpolation object is removed in v5.

docs: remove indexing part from readme

---

src/integrals.jl
test/integral_tests.jl

fixes: #261
`samples` was a function which returned `(0, 1)` for all Interpolations. Not sure why it was needed.

refactor: integral function to correctly compute second index and remove `samples`

---

src/interpolation_methods.jl

If `extrapolate = true`, no need to check bounds.

refactor: check for extrpolate first

---

src/interpolation_utils.jl
test/interface.jl

The interface for, e.g. LinearInterpolation, is not type stable because `cummulative_integral` returns a union. This is because it does a runtime `isempty` check on the methods table. Replacing this with a `hasmethod` check allows the boolean to be determined during compilation, fixing the types.
Note, this does require a slight specialization since `hasmethod` won't match functions that take `::Number` if it's given `Any`.

Fix: type instability in interpolator interface

---

src/derivatives.jl
test/derivative_tests.jl

fixes: #303 
`ub_shift` should be -1

fix: idxs for derivatives in LinearInterpolation

---

src/online.jl
src/parameter_caches.jl
test/interface.jl
test/online_tests.jl

Followup of #304 - Checked type inference of all methods and found some instabilities like:
```julia
julia> @inferred CubicSpline(u, t)
ERROR: return type CubicSpline{ReadOnlyArrays.ReadOnlyVector{Float64, Vector{Float64}}, ReadOnlyArrays.ReadOnlyVector{Float64, Vector{Float64}}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Float64} does not match inferred return type CubicSpline{ReadOnlyArrays.ReadOnlyVector{Float64, Vector{Float64}}, ReadOnlyArrays.ReadOnlyVector{Float64, Vector{Float64}}, _A, _B, Vector{Float64}, Vector{Float64}, Float64} where {_A, _B}
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:35
[2] top-level scope
@ REPL[6]:1
```
Analyzed using Cthulhu and found instability was in the construction of parameter cache.
I have fixed and added all the …

refactor: collect parameters such that they are type stable

---

ext/DataInterpolationsSymbolicsExt.jl
test/interface.jl

fixes: #317
It was missing a dispatch:
```julia
(interp::AbstractInterpolation)(t::BasicSymbolic) = SymbolicUtils.term(interp, t)
```
But then all of them can be combined to just use `register_symbolic` as it does the same thing:
```julia
ulia> @macroexpand @register_symbolic A(t)
quote
begin
#= /home/sathvikbhagavan/.julia/packages/Symbolics/f5Y9e/src/wrapper-types.jl:151 =#
function A_10851946841911346439(nothing, t)
#= /home/sathvikbhagavan/.julia/packages/Symbolics/f5Y9e/src/wrapper-types.jl:124 =#
#= /home/sathvikbhagavan/.julia/packages/Symbolics/f5Y9e/src/wrapper-types.jl:125 =#
begin
#= /home/sathvikbhagavan/.julia/packages/Symbolics/f5Y9e/src/register.jl:32 =#
#= /home/sathvikbhagavan/.julia/packages/Symbolics/f5Y9e/src/register.jl:33 =#
args = [t]
#= …
```

refactor: use register symbolic for interpolation objects

---

Project.toml
docs/Project.toml

#315 was a breaking change.
Also, 5.4.0 is yanked - https://github.com/JuliaRegistries/General/pull/111971

build: bump major version

---

src/interpolation_methods.jl
src/interpolation_utils.jl
src/parameter_caches.jl
test/interpolation_tests.jl

LinearInterpolation: Fix scalar indexing and generalize for ndims(u) > 2

---

src/interpolation_methods.jl
src/parameter_caches.jl
test/interpolation_tests.jl

LinearInterpolation: Output Vector for `u::AbstractMatrix`

---

ext/DataInterpolationsChainRulesCoreExt.jl
src/derivatives.jl
test/derivative_tests.jl
test/zygote_tests.jl

Fixes https://github.com/SciML/DataInterpolations.jl/issues/298 (for matrices and vectors of arrays)

Fix Zygote AD with `u` a matrix or vector of arrays

---

.github/workflows/Downgrade.yml
.github/workflows/Invalidations.yml
src/DataInterpolations.jl
src/derivatives.jl
src/integral_inverses.jl
src/interpolation_caches.jl
src/interpolation_methods.jl
src/interpolation_utils.jl

refactor: add output dimensionality as a parameter in AbstractInterpolations

---

src/interpolation_caches.jl
src/interpolation_methods.jl
src/parameter_caches.jl
test/interpolation_tests.jl

CubicSplines: Add AbstractMatrix support

---

src/interpolation_caches.jl
test/interface.jl

Just doing this from my phone to see if that's it. Missing tests and such, if someone can help that would be great.

Remove hardcoded Float64s in AkimaInterpolation

---

Project.toml

It seems that CompatHelper does not check this one.

Bump Zygote compat to 0.7

---

src/integrals.jl
test/integral_tests.jl
test/interface.jl

This PR fixes and tests some previously untested code paths regarding integrating over an interval that is fully outside the data range.

Fix integrating over interval that is fully outside data range

---

src/DataInterpolations.jl
test/extrapolation_tests.jl
test/interpolation_tests.jl

Do not fall back to inplace interpolation method

---

src/interpolation_utils.jl
test/integral_tests.jl

Related to #389, this PR optimizes `cumulative_integral` by returning `nothing` for non-numeric types. The PR also improves allocations for numeric types a bit.
Fixes #385.
On the master branch:
```julia
julia> A = ConstantInterpolation([3.1, 2.5, 4.7], [0.0, 0.25, 0.75])
julia> DataInterpolations.cumulative_integral(A, false)
Float64[]
julia> DataInterpolations.cumulative_integral(A, true)
2-element Vector{Float64}:
0.775
2.025
julia> f(A, cache_parameters) = @allocations DataInterpolations.cumulative_integral(A, cache_parameters)
julia> f(A, false)
1
julia> f(A, true)
8
julia> using Unitful
julia> A = ConstantInterpolation(rand(5)u"m", (1:5)u"s");
julia> DataInterpolations.integral(A, 4u"s")
ERROR: ArgumentError: zero(Quantity{Float64}) not defined.
...
```
With this PR:
```julia
julia> …
```

Improve `cumulative_integral`

---

Project.toml
src/interpolation_utils.jl
test/interpolation_tests.jl

The PR fixes a few issues related to #389.
On the master branch:
```julia
julia> using DataInterpolations, JET, Chairmarks, Random, Test
julia> @inferred(DataInterpolations.munge_data(["A","B","C"], [0.1,0.2,0.3]))
ERROR: return type Tuple{Vector{String}, Vector{Float64}} does not match inferred return type Tuple{Any, Any}
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:35
[2] top-level scope
@ REPL[33]:1
julia> @report_call ConstantInterpolation(["A", "B", "C"], [0.1, 0.2, 0.3])
═════ 2 possible errors found ═════
┌ ConstantInterpolation(u::Vector{String}, t::Vector{Float64}) @ DataInterpolations /Users/david/.julia/packages/DataInterpolations/dFVzN/src/interpolation_caches.jl:353
│┌ ConstantInterpolation(u::Vector{…}, t::Vector{…}; dir::Symbol, …
```

Fix type inference and performance problems of `munge_data`

---

docs/src/methods.md

Noticed docs build failing on master.

docs: fix link

---

ext/DataInterpolationsRegularizationToolsExt.jl
src/integrals.jl
test/integral_tests.jl

Fixes https://github.com/SciML/DataInterpolations.jl/issues/390

Fix integrating with `cache_parameters = true`

---

Project.toml
docs/Project.toml
docs/src/manual.md
src/DataInterpolations.jl
src/derivatives.jl
src/integral_inverses.jl
src/interpolation_caches.jl
src/interpolation_methods.jl
src/interpolation_utils.jl
test/interpolation_tests.jl

The PR removes the type parameter. I tested with my downstream package and tests finally pass again with this change.
The reason is that
- in general, the output dimension cannot be inferred from `u`
- this implies that the constructor of basically all interpolation methods can't be inferred
- I think it's questionable how useful the information is anyway given that output dimension 3 can refer to `u::Vector{<:Vector}` where each element is of length 3 or e.g. a `u::Matrix` with 3 rows
On the master branch:
```julia
julia> using DataInterpolations, Test
julia> @inferred(ConstantInterpolation([1;; 2;; 3], [0.1, 0.2, 0.3]))
ERROR: return type ConstantInterpolation{Matrix{Int64}, Vector{Float64}, Vector{Union{}}, Int64, (1,)} does not match inferred return type …
```

Remove output dimension type parameter and add `output_dim` to API

---

src/interpolation_utils.jl

Fixes https://github.com/SciML/DataInterpolations.jl/issues/399
Difference between `DataInteprolations.jl` and `PCHIPInterpolation.jl` for the data in the issue:

Fix PCHIP du computation

---

src/derivatives.jl
src/integral_inverses.jl
src/interpolation_methods.jl
test/integral_inverse_tests.jl

I made these changes because I saw some type instabilities when evaluating `LinearInterpolationIntInv`. My hypothesis is that type inference failed because of an infinite recursion (that doesn't happen at runtime). At any rate, the extrapolation functionality now uses a bit more knowledge from those code paths for evaluation too.

Fix type instabilities from extrapolation

---

ext/DataInterpolationsRegularizationToolsExt.jl
src/interpolation_utils.jl
test/interpolation_tests.jl
test/regularization.jl

A frequent user error is forgetting the correct argument error. This results in silently wrong results or extrapolation errors. I think that we can surface this error earlier to avoid further confusion. Let me know what you think about this.

Ensure that the interpolation domain is sorted

---

src/parameter_caches.jl
test/interpolation_tests.jl

This would make interpolation on symbolic arrays work, e.g. 
```julia
@variables x[1:101]
t = 0.:0.01:1
LinearInterpolation(x, t)
```
would work as expected (would throw errors before).

use isequal instead of == in `safe_diff`

---

src/interpolation_utils.jl
test/interpolation_tests.jl

Turns out this contained an uninitialized value.

Fix `get_transition_ts`

---

src/integral_inverses.jl
src/interpolation_caches.jl
src/interpolation_utils.jl
test/integral_inverse_tests.jl
test/interpolation_tests.jl

Before, invert_integral inherits the extrapolation method from the interpolation it got in its construction. 
If we did a piecewise linear interpolation with constant extrapolation, the inverted integral would not integrate beyond the input data. With this change, we can set the extrapolation method of invert_integral independent of the interpolation.

Add optional extrapolation methods

---

src/interpolation_caches.jl

The `uType` parameter is not used in the functions, so remove it and make the function signatures match the same pattern as the others.
The `uType` parametric type is not used in the functions for `QuadraticSpline` so this removes them to match the call signatures of the other interpolation caches.

Remove ununsed `uType`

---

src/interpolation_caches.jl
test/interpolation_tests.jl

Replaces the equivalent of `sqrt(x^2 + y^2)` with `hypot(x, y)` in `BSplineInterpolation` and `BSplineApprox` as `hypot` can be more accurate in some situations and is only marginally slower (~1 ns slower for Float64 arguments). Two tests broke locally due to very minor float changes -- I updated these tests and all now pass locally.
The methods that take `u::AbstractArray` have different expressions that look more like `sqrt(x^2 + sum(y.^2))` which can't be replaced with `hypot` calls so I didn't touch those , e.g.,
https://github.com/SciML/DataInterpolations.jl/blob/618ff4b787cf2 …

Use `hypot` for `BSplineInterpolation`, `BSplineApprox`

---

Project.toml
src/interpolation_caches.jl
src/interpolation_methods.jl
test/interpolation_tests.jl

This hopes to address the performance issues of multi-valued interpolation discussed in #431 by using dependent variable arrays with elements of `StaticArrays.SArray` to remove allocations and improve performance. On `master` this still allocates when evaluating the interpolants, hurting performance.
For the example of `CubicSpline`, I isolated the allocations to come from the `z` array. By converting the elements of `z` to match `eltype(u)`, we are able to remove allocations when evaluating the interpolant and greatly improve the performance. Example usage and performance …

Convert `z` in `CubicSpline` for performance

---

src/show.jl

`show(interp)` currently displays a table with headers `time` and `u`. The actual struct fields are `t` and `u`, described in the docs as "time" and "data," respectively. I find it confusing because most other tables show the property name. Here it tempts me to try `interp.time` which does not exist. 
I propose that the header be changed to `t`, for consistency with `u`.
- all tests still pass, no new tests needed or added
- does not harm public API
- no documentation changes needed or performed
- The new code follows contributor guidelines
An alternative solution would be to update the `u` header to say "data," so that both headers are qualitative descriptors rather than identifiers.
Technically `show` labels multidimensional data as `u1`, `u2`, etc. which also are not actual …

Change header for show method from time to t.

---

src/interpolation_utils.jl
test/derivative_tests.jl
test/integral_tests.jl
test/interpolation_tests.jl

Currently when `Tu === eltype(u) && Tt === eltype(t)`, u, t are returned without the length/size check. This PR moves the check up so incorrect input size are detected correctly. Also changed `@assert` to `cond || error(msg)` form since `@assert`s may be ignored.

length check before return; also explicit error instead of `@assert`
